import 'package:get/get.dart';

class AppTranslator extends Translations {
  @override
  Map<String, Map<String, String>> get keys {
    return <String, Map<String, String>>{
      'en': {
        'Explore': 'Explore',
        'Iran': 'Iran',
        'Theme': 'Theme',
        'Dark Theme': 'Dark Theme',
        'Light Theme': 'Light Theme',
        'Popular': 'Popular',
        'Recomended': 'Recomended',
        'Reviews': 'Reviews',
        'Read More': 'Read More',
        'Wifi': 'Wifi',
        'Dinner': 'Dinner',
        'WC': 'Wc',
        'Pool': 'Pool',
        'Phone:': 'Phone',
        'Email': 'Email',
        'Logout': 'Logout',
        'Cancell': 'Cancell',
        'Are You Sure Want To logout?': 'Are You Sure Want To logout?',
        'Sign Up': 'Sign Up',
        'Name': 'Name',
        'Phone Number': 'Phone Number',
        'Password': 'Password',
        'Re Password': 'Re Password',
        'Register': 'Register',
        'Have a Account? Login': 'Have a Account? Login',
        'Login': 'Login',
        "Don't Have Any Account? Sign Up": "Don't Have Any Account? Sign Up",
        'See Less': 'See Less',
        'Success': 'Success',
        'Welcome!': 'Welcome!',
        'Ok': 'Ok',
        "Tehran was first chosen as the capital of Iran by Agha Mohammad Khan of the Qajar dynasty in 1786, because of its proximity to Iran's territories in the Caucasus, then separated from Iran in the Russo-Iranian Wars, to avoid the vying factions of the previously ruling Iranian dynasties. The capital has been moved several times throughout history, however, and Tehran became the 32nd capital of Persia. Large-scale construction works began in the 1920s, and Tehran became a destination for mass migrations from all over Iran since the 20th century":
            "Tehran was first chosen as the capital of Iran by Agha Mohammad Khan of the Qajar dynasty in 1786, because of its proximity to Iran's territories in the Caucasus, then separated from Iran in the Russo-Iranian Wars, to avoid the vying factions of the previously ruling Iranian dynasties. The capital has been moved several times throughout history, however, and Tehran became the 32nd capital of Persia. Large-scale construction works began in the 1920s, and Tehran became a destination for mass migrations from all over Iran since the 20th century",
        'Warning': 'Warning',
        'Tehran City': 'Tehran City',
        'Pull Down To Refresh': 'Pull Down To Refresh',
        'Release To Refesh': 'Release To Refesh',
        'Refresh Completed': 'Refresh Completed',
        'snakBarMeesage':
            'You can swipe from left to right\nto access the app menu.',
        'Hey': 'Hey!',
        'Tourism Areas': 'Tourism Areas',
        'See': 'See',
        'splashExplore': 'Explore',
      },
      'fa': {
        'Explore': 'نگاهی به',
        'Iran': 'ایران',
        'Theme': 'تم',
        'Dark Theme': 'تم تاریک',
        'Light Theme': 'تم روشن',
        'Popular': 'محبوب ها',
        'Recommended': 'پیشنهادی',
        'Reviews': 'بازدید',
        'Read More': 'بیشتر بخوانید',
        'Wifi': 'وایفای',
        'Dinner': 'رستوران',
        'WC': 'سرویس بهداشتی',
        'Pool': 'استخر',
        'Phone :': 'تلفن :',
        'Email :': 'ایمیل :',
        'Logout': 'خروج',
        'Cancell': 'لغو',
        'Are You Sure Want To logout?':
            'از خروج از حساب کاربری خود اطمینان دارید؟',
        'Sign Up': 'ثبت نام',
        'Name': 'نام',
        'Phone Number': 'شماره تلفن',
        'Password': 'رمز عبور',
        'Re Password': 'تکرار رمزعبور',
        'Register': 'ثبت نام',
        'Have a Account? Login': 'حساب داربد؟ وارد شوید',
        'Login': 'ورود',
        "Don't Have Any Account? Sign Up": 'حساب کاربری ندارید؟ ثبت نام کنید',
        'See Less': 'کمتر ببینید',
        'Success': 'موفقیت آمیز!',
        'Welcome!': 'خوش آمدید!',
        'Ok': 'باشه',
        "Tehran was first chosen as the capital of Iran by Agha Mohammad Khan of the Qajar dynasty in 1786, because of its proximity to Iran's territories in the Caucasus, then separated from Iran in the Russo-Iranian Wars, to avoid the vying factions of the previously ruling Iranian dynasties. The capital has been moved several times throughout history, however, and Tehran became the 32nd capital of Persia. Large-scale construction works began in the 1920s, and Tehran became a destination for mass migrations from all over Iran since the 20th century":
            "تهران اولین بار در سال ۱۷۸۶ توسط آقامحمدخان قاجار به عنوان پایتخت ایران انتخاب شد، به دلیل نزدیکی آن به سرزمین‌های ایران در قفقاز که پس از جنگ‌های ایران و روس از ایران جدا شدند، و برای جلوگیری از رقابت بین جناح‌های مختلف سلسله‌های قبلی ایران. در طول تاریخ، پایتخت چندین بار تغییر کرده است و تهران سی و دومین پایتخت ایران شد. پروژه‌های ساخت‌وساز در مقیاس بزرگ از دهه ۱۹۲۰ آغاز شد و از قرن بیستم به بعد تهران به مقصد مهاجرت‌های گسترده از سراسر ایران تبدیل شد.",
        'Warning': 'هشدار',
        'Tehran City': 'شهر تهران',
        'Pull Down To Refresh': 'برای بارگذاری مجدد به پایین بکشید',
        'Release To Refesh': 'رها کنید',
        'Refresh Completed': 'بارگذاری مجدد انجام شد!',
        'snakBarMeesage':
            'شما میتوانید با کشیدن انگشت از سمت راست به چپ\n وارد منوی برنامه شوید',
        'Hey': 'هی!',
        'See': '',
        'Tourism Areas': 'مناطق توریستی',
        'splashExplore': 'بریم!',
        'Email': 'ایمیل'
      },
    };
  }
}
